'use client'
import React, { useEffect } from "react";
import { Autocomplete } from "@autocomplete/material-ui";
import Input from "../Inputs/Input"
import { useState } from "react";
import Button from "../Button/Button";
import { FaRegAddressCard } from "react-icons/fa6";


const addressesInitial = ["adabor",
    "adabor, adarsha chaya neer",
    "adabor, baitul aman housing society",
    "adabor, comfort housing",
    "adabor, dhaka housing",
    "adabor, ibn sina housing",
    "adabor, janata housing limited",
    "adabor, mehedibagh housing",
    "adabor, mohanpur",
    "adabor, monsurabad residential area",
    "adabor, north adabor",
    "adabor, shyamoli housing limited",
    "adabor, sunibir housing society",
    "aftab nagar",
    "aftabnagar",
    "aftabnagar, block a",
    "aftabnagar, block b",
    "aftabnagar, block c",
    "aftabnagar, block d",
    "aftabnagar, jahurul islam city",
    "aftabnagar, sector 1, jahurul islam city",
    "aftabnagar, sector 2, jahurul islam city",
    "agargaon",
    "agargaon, agargaon administrative area",
    "agargaon, taltola",
    "agargaon, west agargaon",
    "azimpur",
    "azimpur, 3 no bgb gate",
    "azimpur, amtola",
    "azimpur, polashi",
    "azimpur, rasulbagh",
    "babu bazar",
    "babu bazar, bongshi bazar",
    "babu bazar, imamganj",
    "babu bazar, mitford",
    "babu bazar, naya bazar",
    "babu bazar, zindabahar",
    "badda",
    "badda, adarshanagar",
    "badda, anandanagar",
    "badda, dit project",
    "badda, dit project, merul badda",
    "badda, dit project, middle badda",
    "badda, east badda",
    "badda, merul badda",
    "badda, middle badda",
    "badda, mogairdia",
    "badda, north badda",
    "badda, north east badda",
    "badda, padordia, north badda",
    "badda, padordia, satarkul, north badda",
    "badda, satarkul, north badda",
    "badda, south badda",
    "badda, united city",
    "banani",
    "banani, banani dohs",
    "banani, block a",
    "banani, block b",
    "banani, block c",
    "banani, block d",
    "banani, block e",
    "banani, block f",
    "banani, block g",
    "banani, block h",
    "banani, block i",
    "banani, block j",
    "banani, block k",
    "banani, block l",
    "banani, block m",
    "banani, chairman bari",
    "banani, kakoli",
    "banani, soinik club railgate",
    "banasree",
    "banasree, block a",
    "banasree, block b",
    "banasree, block c",
    "banasree, block d",
    "banasree, block e",
    "banasree, block f",
    "banasree, block g",
    "banasree, block h",
    "banasree, block j",
    "banasree, block l",
    "banasree, block m",
    "banasree, south banasree",
    "bangshal",
    "bangshal, ali neki dewri",
    "bangshal, alu bazar",
    "bangshal, armanitola",
    "bangshal, kayet tuli",
    "bangshal, kosaituly",
    "bangshal, mahuttuli",
    "bangshal, malitola",
    "bangshal, mokim bazar",
    "bangshal, nawab katra",
    "bangshal, naya bazar",
    "bangshal, nazira bazar",
    "bangshal, old maghaltuli",
    "bangshal, satraoja",
    "bangshal, shat raoja",
    "bangshal, siddique bazar",
    "bangshal, sikka tuly",
    "bangshal, suritola",
    "baridhara",
    "baridhara dohs",
    "baridhara, baridhara dohs",
    "baridhara, block j",
    "baridhara, block k",
    "bashabo",
    "bashabo, east bashabo",
    "bashabo, kadamtola",
    "bashabo, madartek",
    "bashabo, middle bashabo",
    "bashabo, north bashabo",
    "bashabo, sabujbagh",
    "bashabo, south bashabo",
    "bashundhara",
    "bashundhara r/a",
    "bashundhara, block a",
    "bashundhara, block b",
    "bashundhara, block c",
    "bashundhara, block d",
    "bashundhara, block e",
    "bashundhara, block f",
    "bashundhara, block g",
    "bashundhara, block h",
    "bashundhara, block i",
    "bashundhara, ekuria bazar",
    "bhashantek",
    "bhashantek, baganbari, north bhashantek",
    "bhashantek, benaroshi palli",
    "bhashantek, bhasantek bazar",
    "bhashantek, bhasantek bazar, benaroshi math",
    "bhashantek, bhashantek bazar",
    "bhashantek, block d, ruposhi bangla housing",
    "bhashantek, block ka, benaroshi polli",
    "bhashantek, bostir bazar",
    "bhashantek, dewanpara",
    "bhashantek, dhamalkot",
    "bhashantek, east bhashantek",
    "bhashantek, north bhashantek",
    "bhashantek, shyamol polli residential area, west bhashantek",
    "bhashantek, west bhashantek",
    "buet",
    "chawkbazar",
    "chawkbazar, becharam dewri",
    "chawkbazar, begum bazar",
    "chawkbazar, boro katra",
    "chawkbazar, choto katra",
    "chawkbazar, mitford",
    "chawkbazar, mogholtuli",
    "chawkbazar, moulvibazar",
    "chawkbazar, rahamotganj",
    "chawkbazar, showari ghat",
    "dakhin banasree",
    "dakkhinkhan",
    "dakkhinkhan, ainusbagh",
    "dakkhinkhan, amtola",
    "dakkhinkhan, anol",
    "dakkhinkhan, anwarbagh",
    "dakkhinkhan, ashiyan city",
    "dakkhinkhan, ashkona",
    "dakkhinkhan, ashkona, gawair",
    "dakkhinkhan, atipara",
    "dakkhinkhan, azampur",
    "dakkhinkhan, chairman para",
    "dakkhinkhan, chalabon",
    "dakkhinkhan, coatbari",
    "dakkhinkhan, dakkhinkhan bazar",
    "dakkhinkhan, dakkhinpara",
    "dakkhinkhan, faidabad",
    "dakkhinkhan, gawair",
    "dakkhinkhan, gawair, ashkona",
    "dakkhinkhan, gawair, chalabon",
    "dakkhinkhan, hatimbag",
    "dakkhinkhan, holan",
    "dakkhinkhan, islambagh",
    "dakkhinkhan, joynal market",
    "dakkhinkhan, kawla",
    "dakkhinkhan, kawla, baurartek",
    "dakkhinkhan, koshai bari",
    "dakkhinkhan, koshai bazar railgate",
    "dakkhinkhan, madhubagh",
    "dakkhinkhan, miyapara",
    "dakkhinkhan, modhubagh",
    "dakkhinkhan, mollabari",
    "dakkhinkhan, mollapara",
    "dakkhinkhan, mollartek",
    "dakkhinkhan, mondolbari",
    "dakkhinkhan, moushair",
    "dakkhinkhan, naddapara",
    "dakkhinkhan, nagarbari",
    "dakkhinkhan, nowapara",
    "dakkhinkhan, ponditpara",
    "dakkhinkhan, purbopara",
    "dakkhinkhan, sarderpara",
    "dakkhinkhan, sayednagar",
    "dakkhinkhan, taltola",
    "dhaka airport",
    "dhaka cantonment",
    "dhaka cantonment, albodirtek",
    "dhaka cantonment, baganbari",
    "dhaka cantonment, baigartek",
    "dhaka cantonment, balughat",
    "dhaka cantonment, barontek",
    "dhaka cantonment, cantonment residential area",
    "dhaka cantonment, dholaikhal",
    "dhaka cantonment, garrison",
    "dhaka cantonment, kachukhet",
    "dhaka cantonment, manikdi",
    "dhaka cantonment, manikdi, matikata",
    "dhaka cantonment, matikata",
    "dhaka cantonment, nirjhor residential area",
    "dhaka cantonment, zia colony",
    "dhaka university",
    "dhanmondi",
    "dhanmondi, green square",
    "dhanmondi, jafrabad",
    "dhanmondi, jafrabad, sankar",
    "dhanmondi, jigatola",
    "dhanmondi, madhu bazar",
    "dhanmondi, north dhanmondi",
    "dhanmondi, sankar",
    "dhanmondi, science laboratory",
    "dhanmondi, shukrabad",
    "dhanmondi, sobhanbagh",
    "dhanmondi, west dhanmondi",
    "dholairpar",
    "dholairpar, dholairpar bazar",
    "dholairpar, east dholairpar",
    "eskaton",
    "eskaton, bangla motor",
    "eskaton, new eskaton",
    "eskaton, pwd quater",
    "fakirapul",
    "fakirapul, fakirapul bazar",
    "golapbagh",
    "golapbagh, brammon chiron",
    "golapbagh, east golapbagh",
    "golapbagh, kazirbagh",
    "golapbagh, north golapbagh",
    "golapbagh, rishi para",
    "gulisthan",
    "gulisthan, alu bazar",
    "gulisthan, fulbaria",
    "gulisthan, siddique bazar",
    "gulisthan, zero point",
    "gulshan",
    "gulshan, gulshan 1",
    "gulshan, gulshan 2",
    "gulshan, niketon",
    "hatirpool",
    "hatirpool, pukurpar",
    "hazaribagh",
    "hazaribagh, badda nagar",
    "hazaribagh, bagholpur",
    "hazaribagh, bhuiyan estate",
    "hazaribagh, borhanpur",
    "hazaribagh, charakghata",
    "hazaribagh, company ghat",
    "hazaribagh, enayetganj",
    "hazaribagh, gajmahal",
    "hazaribagh, gonokatuli",
    "hazaribagh, hazaribagh bazar",
    "hazaribagh, hazaribagh model city",
    "hazaribagh, jhauchor",
    "hazaribagh, jhauchor model town",
    "hazaribagh, kalu nagar",
    "hazaribagh, moneshwar",
    "hazaribagh, nabipur",
    "hazaribagh, nawabganj",
    "hazaribagh, shikder real state",
    "hazaribagh, sonatongor",
    "hazaribagh, tannery block",
    "hazaribagh, tannery moar",
    "hazaribagh, west hazaribagh",
    "joar shahara",
    "joar shahara, balur math",
    "joar shahara, himbari",
    "joar shahara, joar shahara bazar",
    "joar shahara, lichu bagan",
    "joar shahara, olipara",
    "kakrail",
    "kalabagan",
    "kalabagan, green view area",
    "kalabagan, lake circus",
    "kalachadpur",
    "kalachandpur",
    "kalachandpur, moddhopara",
    "kalachandpur, poshchimpara",
    "kalachandpur, uttarpara",
    "kallyanpur",
    "kallyanpur, banoful residential area",
    "kallyanpur, eastern housing 2",
    "kallyanpur, kallyanpur notun bazar",
    "kallyanpur, navana garden society",
    "kallyanpur, rojonigondha residential area",
    "kallyanpur, south kallyanpur",
    "kamalapur",
    "kamalapur, north kamalapur",
    "kamalapur, south kamalapur",
    "kathalbagan",
    "kathalbagan, box culvert",
    "kathalbagan, pukurpar",
    "khilgaon",
    "khilgaon, block a",
    "khilgaon, block c",
    "khilgaon, bou bazar",
    "khilgaon, chowdhurypara",
    "khilgaon, gouranagar",
    "khilgaon, jheelpar",
    "khilgaon, jorapukur para",
    "khilgaon, khilgaon punorbason area",
    "khilgaon, khilgaon shati elma residential area",
    "khilgaon, khilgaon somaj kallyan society",
    "khilgaon, khilgaon south society",
    "khilgaon, moulovirtek",
    "khilgaon, moulovirtek residential area",
    "khilgaon, nandipara",
    "khilgaon, nobinbagh",
    "khilgaon, notunbagh",
    "khilgaon, riajbagh",
    "khilgaon, saherunbagh",
    "khilgaon, shantipur",
    "khilgaon, sipahibagh",
    "khilgaon, south khilgaon",
    "khilgaon, taltola",
    "khilgaon, tilpapara",
    "khilgaon, trimohoni",
    "khilkhet",
    "khilkhet, aburtek",
    "khilkhet, amtola",
    "khilkhet, barua",
    "khilkhet, beparipara",
    "khilkhet, boatghat",
    "khilkhet, bottola",
    "khilkhet, dorjipara",
    "khilkhet, kha para",
    "khilkhet, khilkhet bazar",
    "khilkhet, lake city concord",
    "khilkhet, moddhopara",
    "khilkhet, moddhopara bazar",
    "khilkhet, namapara",
    "khilkhet, namapara, talertek",
    "khilkhet, naval area",
    "khilkhet, naya nagar",
    "khilkhet, tetultola",
    "khilkhet, uttarpara",
    "kolabagan",
    "korail",
    "korail, bou bazar",
    "korail, jamai bazar",
    "kuril",
    "kuril, ghatpar",
    "kuril, kazi bari",
    "kuril, kazibari",
    "kuril, kuratoli",
    "kuril, kuril chowrasta",
    "kuril, miya bari",
    "kuril, moddhopara",
    "kuril, purbopara",
    "kuril, south kuril",
    "lalbagh",
    "lalbagh, amligola",
    "lalbagh, chadni ghat",
    "lalbagh, chowdhury bazar",
    "lalbagh, dhakeshwari",
    "lalbagh, islambagh",
    "lalbagh, islampur",
    "lalbagh, kashmiritola",
    "lalbagh, khaje dewan",
    "lalbagh, killar moar",
    "lalbagh, nawabganj",
    "lalbagh, palashi",
    "lalbagh, pilkhana",
    "lalbagh, posta",
    "lalbagh, rasulbagh",
    "lalbagh, shahidnagar",
    "lalbagh, sheikh shaheb bazar",
    "lalmatia",
    "lalmatia, block a",
    "lalmatia, block b",
    "lalmatia, block c",
    "lalmatia, block d",
    "lalmatia, block e",
    "lalmatia, block f",
    "lalmatia, block g",
    "malibagh",
    "malibagh, baganbari",
    "malibagh, chowdhurypara",
    "malibagh, east malibagh",
    "malibagh, gulbagh",
    "malibagh, malibagh railgate bazar",
    "malibagh, mouchak",
    "malibagh, sonalibagh",
    "malibagh, west malibagh",
    "manikdi",
    "maniknagar",
    "maniknagar, east maniknagar",
    "maniknagar, kazirbagh",
    "maniknagar, north maniknagar",
    "meradia",
    "meradia, ansarbagh",
    "meradia, bhuiyapara",
    "meradia, hindupara",
    "meradia, meradia bazar",
    "meradia, moddhopara",
    "meradia, nayapara",
    "meradia, noapara",
    "meradia, west meradia",
    "mirpur",
    "mirpur dohs",
    "mirpur, 1st colony",
    "mirpur, 1st colony, lalkuthi",
    "mirpur, 2nd colony",
    "mirpur, 3rd colony",
    "mirpur, ahmed nagar",
    "mirpur, ahmed nagar, paikpara",
    "mirpur, al kamal housing",
    "mirpur, alubdi",
    "mirpur, ananda nagar",
    "mirpur, arambagh",
    "mirpur, arifabad housing",
    "mirpur, baghbari",
    "mirpur, baishteki",
    "mirpur, baishteki, section 13",
    "mirpur, bardhan bari",
    "mirpur, basupara",
    "mirpur, basupara, lalkuthi",
    "mirpur, batennagar",
    "mirpur, bcic colony",
    "mirpur, bishil",
    "mirpur, borobagh",
    "mirpur, borobazar",
    "mirpur, box nagar",
    "mirpur, darussalam",
    "mirpur, diabari",
    "mirpur, duaripara",
    "mirpur, eastern housing",
    "mirpur, extension pallabi",
    "mirpur, gabtoli",
    "mirpur, godkhali",
    "mirpur, golartek",
    "mirpur, goran chotbari",
    "mirpur, gudaraghat, section 1",
    "mirpur, harirampur",
    "mirpur, jahanabad",
    "mirpur, jahurabad",
    "mirpur, janata housing",
    "mirpur, kabarsthan gate",
    "mirpur, kalwalapara",
    "mirpur, kazipara",
    "mirpur, kotbari",
    "mirpur, lalkuthi",
    "mirpur, mirpur cantonment",
    "mirpur, mirpur dohs",
    "mirpur, monipur",
    "mirpur, muktijoddha complex",
    "mirpur, nababerbagh",
    "mirpur, paikara",
    "mirpur, paikpara",
    "mirpur, pallabi",
    "mirpur, pirerbagh",
    "mirpur, priyanka housing",
    "mirpur, rayhan market",
    "mirpur, royal city",
    "mirpur, rupnagar",
    "mirpur, rupnagar industrial area",
    "mirpur, sagufta housing society",
    "mirpur, section 1",
    "mirpur, section 10",
    "mirpur, section 11",
    "mirpur, section 12",
    "mirpur, section 13",
    "mirpur, section 13, baishteki",
    "mirpur, section 14",
    "mirpur, section 15",
    "mirpur, section 2",
    "mirpur, section 3",
    "mirpur, section 6",
    "mirpur, section 7",
    "mirpur, section 8",
    "mirpur, section 9",
    "mirpur, senpara",
    "mirpur, senpara parbata",
    "mirpur, shagufta",
    "mirpur, shagufta housing",
    "mirpur, shah ali bagh",
    "mirpur, shahid buddijibi area",
    "mirpur, shewrapara",
    "mirpur, technical",
    "mirpur, tolarbagh",
    "moghbazar",
    "moghbazar, boro moghbazar",
    "moghbazar, mirbagh",
    "moghbazar, mirertek",
    "moghbazar, modhubagh",
    "moghbazar, noyatola",
    "moghbazar, pearabagh",
    "moghbazar, sonalibagh",
    "moghbazar, tnt colony",
    "moghbazar, wireless",
    "moghbazar, wireless railgate",
    "mohakhali",
    "mohakhali, amtoli",
    "mohakhali, dakkhinpara",
    "mohakhali, korail",
    "mohakhali, mohakhali bazar",
    "mohakhali, mohakhali commercial area",
    "mohakhali, mohakhali dohs",
    "mohakhali, mohakhali wireless",
    "mohakhali, muktijoddha chaoni c&b taltola",
    "mohakhali, muktijoddha chaoni dakkhin para",
    "mohakhali, ôªøwireless gate",
    "mohakhali, rasulbagh",
    "mohakhali, south mohakhali",
    "mohakhali, tb gate",
    "mohakhali, wireless gate",
    "mohammadpur",
    "mohammadpur, ajij mahalla",
    "mohammadpur, akkas nagar",
    "mohammadpur, akota housing",
    "mohammadpur, asad gate",
    "mohammadpur, bashbari",
    "mohammadpur, basila",
    "mohammadpur, basila, metro housing",
    "mohammadpur, bijli mahalla",
    "mohammadpur, bijli mahalla, jannatbagh",
    "mohammadpur, block a",
    "mohammadpur, block b",
    "mohammadpur, block c",
    "mohammadpur, block d",
    "mohammadpur, block e",
    "mohammadpur, block f",
    "mohammadpur, chad uddyan",
    "mohammadpur, chand miya housing",
    "mohammadpur, chandrima model town",
    "mohammadpur, college gate",
    "mohammadpur, dhaka uddyan",
    "mohammadpur, future housing",
    "mohammadpur, future model town",
    "mohammadpur, geneva camp",
    "mohammadpur, green view housing",
    "mohammadpur, jafrabad",
    "mohammadpur, jahuri mahalla",
    "mohammadpur, joint quarter, aziz mahalla",
    "mohammadpur, katashur",
    "mohammadpur, krishi market",
    "mohammadpur, masjid market",
    "mohammadpur, metropolitan housing society",
    "mohammadpur, mohammadia housing",
    "mohammadpur, mohammadia housing society",
    "mohammadpur, nabinagar housing",
    "mohammadpur, nobodoy housing",
    "mohammadpur, nobodoy housing limited",
    "mohammadpur, nobodoy housing society",
    "mohammadpur, pisci culture housing society",
    "mohammadpur, pisciculture housing society",
    "mohammadpur, rajdhani housing",
    "mohammadpur, rayer bazar",
    "mohammadpur, saat masjid housing",
    "mohammadpur, shaymoli housing limited",
    "mohammadpur, shekhertek",
    "mohammadpur, shyamoli housing",
    "mohammadpur, swapnodhara housing",
    "mohammadpur, tikkapara",
    "mohammadpur, tin raster moar",
    "mohammadpur, town hall",
    "mohammadpur, turag housing",
    "mohammadpur, west dhanmondi residential area, basila",
    "motijheel",
    "motijheel, agb colony",
    "motijheel, arambagh",
    "motijheel, bank colony",
    "motijheel, dilkusha commercial area",
    "motijheel, fakirapul",
    "motijheel, motijheel commercial area",
    "motijheel, motijheel government colony",
    "motijheel, tnt colony",
    "mugda",
    "mugda, bank colony",
    "mugda, green model town",
    "mugda, north mugda",
    "mugda, sabujkanan",
    "mugda, south mugda",
    "nadda",
    "nadda, morol bazar",
    "nadda, nadda bazar",
    "nadda, nurerchala",
    "nadda, purbopara",
    "nadda, sarkerbari",
    "naya bazar",
    "naya bazar, zindabahar",
    "new eskaton",
    "new eskaton, bangla motor",
    "new eskaton, gaus nagar",
    "new market",
    "new market, bata signal",
    "new market, katabon",
    "new market, nilkhet",
    "new market, science laboratory",
    "niketon",
    "nikunja",
    "nikunja, nikunja 1",
    "nikunja, nikunja 2",
    "over sea",
    "paltan",
    "paltan, bijoynagar",
    "paltan, naya paltan",
    "paltan, purana paltan",
    "paribagh",
    "pilkhana",
    "rajarbagh",
    "rajarbagh, chamelibagh",
    "rajarbagh, momenbagh",
    "ramna",
    "ramna, nawratan colony",
    "rampura",
    "rampura, east rampura",
    "rampura, hazipara",
    "rampura, mohanagar project",
    "rampura, west rampura",
    "rayer bazar",
    "rayer bazar, baroikhali",
    "rayer bazar, bottola",
    "rayer bazar, chorokghata",
    "rayer bazar, east rayer bazar",
    "rayer bazar, jafrabad",
    "rayer bazar, modhubazar",
    "rayer bazar, nimtola",
    "rayer bazar, rayer bazar model town",
    "rayer bazar, sultanganj",
    "rayer bazar, sultanganj, baroikhali",
    "rayer bazar, west dhanmondi",
    "sabujbagh",
    "sabujbagh, ahmedbagh",
    "sabujbagh, bashabo",
    "sabujbagh, begunbari",
    "sabujbagh, dakkhingaon",
    "sabujbagh, east rajarbagh",
    "sabujbagh, kusumbagh",
    "sabujbagh, madartek",
    "sabujbagh, manikdia",
    "sabujbagh, mayakanon",
    "sabujbagh, rajarbagh",
    "shahbag",
    "shahjadpur",
    "shahjadpur, bashtola",
    "shahjadpur, east shahjadpur",
    "shahjadpur, jheelpar",
    "shahjadpur, shahjadpur bus stand",
    "shahjadpur, south shahjadpur",
    "shahjahanpur",
    "shahjahanpur, benjir baganbari residential area",
    "shahjahanpur, north shahjahanpur",
    "shahjahanpur, railway government colony",
    "shahjahanpur, railway staff colony",
    "shahjahanpur, shahidbagh",
    "shahjahanpur, south shahjahanpur",
    "shanir akhra",
    "shanir akhra, kadamtali",
    "shantibagh",
    "shantibagh, west shantibagh",
    "shantinagar",
    "shantinagar, aminbagh",
    "shantinagar, chamelibagh",
    "shantinagar, shantinagar bazar",
    "shegunbagicha",
    "sher e bangla nagar",
    "shukrabad",
    "shyamoli",
    "shyamoli, block b",
    "shyamoli, block c",
    "shyamoli, khalpar",
    "shyamoli, north shyamoli",
    "shyamoli, pisciculture housing society",
    "siddheshwari",
    "siddheshwari, mouchak",
    "tejgaon",
    "tejgaon, arjatpara",
    "tejgaon, babli",
    "tejgaon, begunbari",
    "tejgaon, farmgate",
    "tejgaon, jahanara garden",
    "tejgaon, kawran bazar",
    "tejgaon, kunipara",
    "tejgaon, monipuripara",
    "tejgaon, nakhalpara",
    "tejgaon, rajabazar",
    "tejgaon, shahinbag",
    "tejgaon, shahinbagh",
    "tejgaon, shanti niketon residential area",
    "tejgaon, tejgaon industrial area",
    "tejgaon, tejkunipara",
    "tejgaon, tejturi bazar",
    "tikatuli",
    "tikatuli, eastern housing",
    "tikatuli, hatkhola",
    "tikatuli, shamibagh",
    "uttara",
    "uttara, abdullahpur",
    "uttara, badshartek",
    "uttara, diabari",
    "uttara, dolipara",
    "uttara, sector 1",
    "uttara, sector 10",
    "uttara, sector 11",
    "uttara, sector 12",
    "uttara, sector 13",
    "uttara, sector 14",
    "uttara, sector 15",
    "uttara, sector 16",
    "uttara, sector 17",
    "uttara, sector 18",
    "uttara, sector 3",
    "uttara, sector 4",
    "uttara, sector 5",
    "uttara, sector 6",
    "uttara, sector 7",
    "uttara, sector 8",
    "uttara, sector 9",
    "vatara",
    "vatara, barobigha",
    "vatara, east vatara",
    "vatara, east vatara, sayednagar",
    "vatara, jagannathpur",
    "vatara, khilbarirtek",
    "vatara, nadda",
    "vatara, nadda bus stand",
    "vatara, nayabari",
    "vatara, nayanagar",
    "vatara, notun bazar",
    "vatara, nurerchala",
    "vatara, sayednagar",
    "vatara, sayeed nagar",
    "vatara, solmaid",
    "vatara, vatara moar",
    "vatara, west vatara",
    "wari",
    "wari, banagram",
    "wari, baniyanagar",
    "wari, dholaikhal",
    "wari, gopibagh",
    "wari, hatkhola",
    "wari, kaptan bazar",
    "wari, murgipotti",
    "wari, murgitola",
    "wari, mushundi",
    "wari, narinda",
    "wari, robidhash para",
    "wari, thatari bazar",]


function AddAddress({ visible, showModal }) {


    const [text, setText] = useState({ value: '' });
    const [addresses, setAddresses] = useState(addressesInitial);
    const [showList, setShowList] = useState(false)

    const handleFilterChange = () => {

        const filteredAddresses = addressesInitial.filter((address) =>
            address.toLowerCase().includes(text?.value?.toLowerCase() || "")
        );

        setAddresses(filteredAddresses);
    };

    useEffect(() => {
        handleFilterChange()
    }, [text])


    function setAnAddress(address) {
        setText({ value: address });
        setShowList(false)
    }

    function resetAddress() {
        setText({ value: "" });
        setShowList(false)
    }

    function closeModalWithDelay() {
        setTimeout(() => {
            showModal(p => !p)
        }, 1500);
    }


    const addressElements = <>
        {
            addresses.map(address => (
                <Button key={address} onClick={() => setAnAddress(address)} className="border h-10 w-full hover:rounded-md hover:scale-110 " >
                    {address}
                </Button>
            ))
        }
    </>

    if (!visible) return null;
    return (
        <div
            className=" fixed inset-0 z-[300] text-primary bg-background bg-opacity-75 backdrop-blur-md flex flex-col justify-center items-center" >

            <div
                className="w-[500px] h-auto rounded-md  z-[201]" >
                <div className="relative backdrop-blur-2xl  ">

                    {text?.value && !showList && <div className="w-full h-10 text-primary pl-2 " > You have selected :- </div>}

                    <div className=" h-auto flex flex-row items-center justify-center py-1 px-2 rounded-md overflow-hidden border border-gray-600">
                        <Input
                            name={"address"} onChange={setText} value={text.value} placeholder={"Select your address"} type={"text"}
                            onFocus={() => setShowList(true)}
                            className={`w-full h-10 active:border-none active:outline-none focus:border-none focus:outline-none `} />
                        <span onClick={resetAddress} className=" w-7 h-7 cursor-pointer " >X</span>
                    </div>

                    {
                        showList &&
                        <div className=" h-fit max-h-96 overflow-y-scroll overflow-x-hidden" >
                            {addressElements}
                            {addresses?.length === 0 && <div className="w-full h-10 text-red-600 " > No address found..! </div>}
                        </div>}


                </div>
            </div>

            <div className="h-10 mt-10 " >
                <Button onClick={closeModalWithDelay} > Add Address <span className="scale-125" > <FaRegAddressCard /> </span>  </Button>
            </div>

        </div>
    )
}
export default AddAddress

