import "./globals.css";
import { Inter } from "next/font/google";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import SessionProvider from "./components/contexts/SessionProvider";
import { getServerSession } from "next-auth";
import Navbar from "./components/Navbar/Navbar";
import CartModal from "./components/Modals/CartModal";
import NavBarWrapper from "./components/Navbar/NavBarWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={`h-screen  bg-background text-[#00FFFF]`}>
          <NavBarWrapper />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
